name: Deploy to VPS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build the Go app
      run: go build -o app .

    - name: Deploy via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 89.207.255.98
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "app"
        target: "/opt/probhub/simple1"

    - name: Run the app via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 89.207.255.98
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          pkill app || true
          nohup /opt/probhub/simple1/app/app > /opt/probhub/simple1/app/log.txt 2>&1 &
